// <auto-generated />
using BTLOP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTLOP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260413073651_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTLOP.Models.DangKi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KhoaHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SinhVienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("dk");
                });

            modelBuilder.Entity("BTLOP.Models.KhoaHoc", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("moTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("kh");
                });

            modelBuilder.Entity("BTLOP.Models.SinhVien", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("sv");
                });

            modelBuilder.Entity("BTLOP.Models.DangKi", b =>
                {
                    b.HasOne("BTLOP.Models.KhoaHoc", "kh")
                        .WithMany("DangKis")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTLOP.Models.SinhVien", "sv")
                        .WithMany("DangKis")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kh");

                    b.Navigation("sv");
                });

            modelBuilder.Entity("BTLOP.Models.KhoaHoc", b =>
                {
                    b.Navigation("DangKis");
                });

            modelBuilder.Entity("BTLOP.Models.SinhVien", b =>
                {
                    b.Navigation("DangKis");
                });
#pragma warning restore 612, 618
        }
    }
}
