// <auto-generated />
using System;
using Code_First.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Code_First.Migrations
{
    [DbContext(typeof(ThuVienContext))]
    [Migration("20260408060745_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChiTietPhieuMuon", b =>
                {
                    b.Property<int>("MaCT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCT"));

                    b.Property<string>("MaPM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhieuMuonMaPM")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SachMaSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCT");

                    b.HasIndex("PhieuMuonMaPM");

                    b.HasIndex("SachMaSach");

                    b.ToTable("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("Code_First.Models.DocGia", b =>
                {
                    b.Property<string>("MaDG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDG");

                    b.ToTable("DocGias");
                });

            modelBuilder.Entity("Code_First.Models.Sach", b =>
                {
                    b.Property<string>("MaSach")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSach");

                    b.ToTable("Sachs");
                });

            modelBuilder.Entity("PhieuMuon", b =>
                {
                    b.Property<string>("MaPM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocGiaMaDG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaDG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPM");

                    b.HasIndex("DocGiaMaDG");

                    b.ToTable("PhieuMuons");
                });

            modelBuilder.Entity("ChiTietPhieuMuon", b =>
                {
                    b.HasOne("PhieuMuon", "PhieuMuon")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("PhieuMuonMaPM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Code_First.Models.Sach", "Sach")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("SachMaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuMuon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("PhieuMuon", b =>
                {
                    b.HasOne("Code_First.Models.DocGia", "DocGia")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("DocGiaMaDG");

                    b.Navigation("DocGia");
                });

            modelBuilder.Entity("Code_First.Models.DocGia", b =>
                {
                    b.Navigation("PhieuMuons");
                });

            modelBuilder.Entity("Code_First.Models.Sach", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("PhieuMuon", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");
                });
#pragma warning restore 612, 618
        }
    }
}
